### ISSUE TITLE
Error in compiling Timeloop and soultion

### ISSUE THREAD

**Issue by midiareshadi** [Accelergy-Project/accelergy-timeloop-infrastructure#1]
Hi,
First of all, thanks for your great workshop (Sparse Tensor @ISCA2021).
I encountered the following error in compiling the [Timeloop @ 2d4a244](https://github.com/NVlabs/timeloop/tree/2d4a24413856521a57ac17824779f1f0023fefe2).
```
src/loop-analysis/nest-analysis-tile-info.cpp:50:15: error: ‘accumulate’ is not a member of ‘std’
   50 |   return std::accumulate(accesses.begin(), accesses.end(), static_cast<std::uint64_t>(0));
      |               ^~~~~~~~~~
scons: *** [build/loop-analysis/nest-analysis-tile-info.o] Error 1
scons: building terminated because of errors.
```
And the solution is adding `#include <numeric>` to [nest-analysis-tile-info.cpp](https://github.com/NVlabs/timeloop/blob/2d4a24413856521a57ac17824779f1f0023fefe2/src/loop-analysis/nest-analysis-tile-info.cpp)
I compiled Timeloop in the following distribution:
_Ubuntu 20.04 LTS (focal)_

**Comment by nellie-wu** [comment]
Thanks for the kind note, we will update timeloop accordingly.
