### ISSUE TITLE
Version of Those Libraries

### ISSUE THREAD

**Issue by ScopeX-ASU** [Accelergy-Project/accelergy-timeloop-infrastructure#20]
I noticed the installation script is for Debian machines. For RedHat/CentOS system, what are the proper versions of those libraries? I installed those libraries, and compiled with "scons -j4 --with-isl --accelergy", it fails with many errors: "undefined symbols..." in boost/yaml-cpp/libconfig. "--static" fails to find those "-lpthread, -lboost...." libraries.
I was wondering it might be a problem with library version mismatch. What are the proper versions for those libraries

**Comment by tanner-andrulis** [comment]
Have you installed all of the following:
```
apt-get update
apt-get install -y vim
apt-get install python3-pip
apt-get install -y libconfig++-dev
apt-get install -y libboost-dev
apt-get install -y libboost-iostreams-dev
apt-get install -y libboost-serialization-dev
apt-get install -y libyaml-cpp-dev
apt-get install -y libncurses-dev
apt-get install -y libtinfo-dev
apt-get install -y libgpm-dev
```

If it doesn't work after this install, I would recommend asking in the main Timeloop repository (where the Timeloop devs are). They should have the exact versions for you.

**Comment by tanner-andrulis** [comment]
I'm seeing now that you asked there as well. Please only ask questions in one location. Duplicates are not respectful of our time.
