### ISSUE TITLE
Two minor typos in README.md

### ISSUE THREAD

**Issue by midiareshadi** [Accelergy-Project/accelergy-timeloop-infrastructure#3]
There are two minor typos in the git command of [README.md](https://github.com/Accelergy-Project/accelergy-timeloop-infrastructure/blob/master/README.md) file:
The first one is in:
### Native Install
``
% git clone --recurse-submodules https://github.com/Accelergy-Project/accelergy-timeloop-infrastucture.git
``

and the second is in:
### Build the image
``
% git clone --recurse-submodules https://github.com/Accelergy-Project/accelergy-timeloop-infrastucture.git
``

For both of them the correct git command is:

``
% git clone --recurse-submodules https://github.com/Accelergy-Project/accelergy-timeloop-infrastructure.git
``

**Comment by jsemer** [comment]
Thank you. Typos now fixed
